DROP TABLE IF EXISTS `LotLastPicked`;
CREATE TABLE `LotLastPicked` (
	`CustomerID` VARCHAR(64) NOT NULL,
	`ProductCode` VARCHAR(32) NOT NULL,
	`LotID` VARCHAR(64) NOT NULL,
	`LotNumber` VARCHAR(64),
	`CreateDate` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CustomerID,ProductCode),
  KEY LotID (LotID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
