ALTER TABLE `Offer`
ADD COLUMN Transferred TINYINT NOT NULL DEFAULT 0 AFTER OCSContactEmail;

ALTER TABLE `Lot`
ADD COLUMN Transferred TINYINT NOT NULL DEFAULT 0 AFTER StatusPID,
ADD COLUMN TransferredFrom VARCHAR(64) NULL AFTER StatusPID;
