<?php

$rContent = '';
$this->partial(
	"include/header",
	array(
		'title' => $title,
		'header' => $title,
		'headerIcon' => 'edi',
		'rightContent' => $rContent
	)
);
?>
<div id="subtitlelinks">
	<a href="/customerorder/list/">See Incoming Orders</a>
</div>

<?php
if ( isset( $details ) ) {
	$this->partial(
		"table/details",
		array(
			'details' => $details
		)
	);
}

$this->partial(
	"table/builder",
	array(
		'headers' => $headers,
		'data' => $data,
		'cols' => $cols
	)
);
?>

<?php
$this->partial("include/footer_start");
?>
<style>
.bootbox-body h5 {
	font-size: 1.2em;
	text-transform: uppercase;
	text-align: left;
	font-weight: bold;
	letter-spacing: 0.2em;
	color: #d6bd99;
	margin-bottom: .5rem;
}
</style>
<script>
jQuery(document).ready(function($) {
	$( '#autotable tr' ).click( function(){
		rowid = $( this ).attr( 'id' ); // OfferID
		parts = rowid.split( ':' );
		location.href = '/offer/edit/' + parts[1];
	});
});
</script>




<?php
$this->partial("include/footer_end");
