<style>
	#ship-sell-button {
		margin: 0 auto;
		width: fit-content;
		padding-left: 65px;
	}
	/* Dropdown Button */
	.dropbtn,
	#mainbtn {
		background-color: #680000;
		border-color: #4f0000;
		color: white;
		padding: 7px;
		font-size: 14px;
		border: none;
		cursor: pointer;
		margin: 0;
		height: 33px;
		vertical-align: top;
		display: inline-block;
	}

	#mainbtn {
		border-top-left-radius: 14px;
		border-bottom-left-radius: 14px;
		width: 142px;
	}

	.dropbtn {
		padding-right: 11px;
		border-top-right-radius: 14px;
		border-bottom-right-radius: 14px;
	}

	/* Dropdown button on hover & focus */
	.dropbtn:hover,
	.dropbtn:focus,
	#mainbtn:hover {
		/*   background-color: #2980B9; */
		color: #fba344;
	}

	/* The container <div> - needed to position the dropdown content */
	.dropdown {
		position: absolute;
		display: block;
		width: fit-content;
	}

	/* Dropdown Content (Hidden by Default) */
	.dropdown-content {
		display: block;
		position: relative;
		background-color: #f1f1f1;
		box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
		z-index: 1;
		max-height: 0;
		height: fit-content;
		transition: max-height 400ms ease-in-out;
		overflow: hidden;
		left: 4px;
	}

	/* Links inside the dropdown */
	.dropdown-content a {
		position: relative;
		color: black;
		padding: 7px 12px;
		text-decoration: none;
		display: block;
	}

	/* Change color of dropdown links on hover */
	.dropdown-content a:hover {
		background-color: #ddd;
	}

	.dropbtn .fa-chevron-down.fa-lg {
		font-size: 75%;
		vertical-align: 2px;
	}

	/* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
	.show {
		max-height: 500px;
	}

	.disabled-button-option {
		color: dimgray !important;
		background-color: #f1f1f1 !important;
	}

	.disabled-button-option:hover {
		cursor: not-allowed;
	}
</style>
<div id="ship-sell-button">

	<!-- NOTE: if EDI, don't allow quick ship. -->
	<?php if ( $isEDI ): ?>
		<button id="sellButton" type="button" class="btn btn-primary" style="margin-right: -40px;">Mark Offer SOLD</button>
	<?php else: ?>
		<button id="mainbtn" data-action="sell" type="button">Mark Offer SOLD</button><button type="button" class="dropbtn"><i class="fa fa-chevron-down fa-lg fa-fw"></i></button>
		<div class="dropdown">
			<div id="myDropdown" class="dropdown-content">
				<a id="markSoldButton" href="#" data-action="sell" class="button-option">Mark Offer SOLD</a>
				<a id="sellAndShipButton" href="#" data-action="ship" class="button-option">SELL & SHIP Offer</a>
				<a id="transferButton" href="#" data-action="transfer" class="button-option disabled-button-option" disabled>TRANSFER to Lot</a>
			</div>
		</div>
	<?php endif; ?>
</div>

