<?php
$this->partial(
	"include/print_header",
	[
		'title' => 'Warehouse Receipt #' . $receiptData['ReceiptNumber'],
		'stylesheets' => [
			'//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css',
			'/public/css/bootstrap-modal-only.css'
		]
	]
);

$nextPageItems = count($items) ? $items : TRUE;

$maxPoints = 226; // 240; // 225 = 3.125 inches
$lineHeightPoints = 13.5;
$cellHeightPoints = 12;
$tableExtraPoints = 3;

$sideMargin = '1.125in';

$LOTS_PER_PAGE = 5;

while ($nextPageItems) {
	$pageItems = $nextPageItems;
	$nextPageItems = NULL;

	$approxPoints = 0.0;
?>
	<div class="page shorten-for-print">
		<div class="page-inner">

			<img src="/public/images/Warehouse_Receipt_P1.jpg" class="page-background" />

			<div class="absolute with-line center" style="left: 6.25in; bottom: 9.625in; right: <?= $sideMargin ?>;"><?= $receiptData['ReceiptNumber'] ?></div>

			<div id="facilityName" class="absolute with-line center" style="bottom: 9.295in; width: 100%;font-size: 24px;font-weight: bold;text-transform: uppercase;"></div>

			<div id="facilityAddress" class="absolute with-line center" style="bottom: 8.74in;width: 100%;font-size: 14px;font-weight: bold;"></div>

			<div id="facilityNameFooter1" class="absolute with-line" style="bottom: 2.58in;font-size: 20px;font-weight: bold;right: 10rem;width: 307px;text-transform: uppercase;">
				<div class="facilityNameFooter1" style="display: flex;justify-content: center;"></div>
			</div>

			<div id="facilityNameFooter2" class="absolute with-line" style="bottom: 1.45in;font-size: 15px;font-weight: bold;width: 307px;right: 10rem;">
				<div class="facilityNameFooter2" style="display: flex;justify-content: center;"></div>
			</div>

			<div class="absolute with-line center" style="left: 4.625in; bottom: 8.425in; right: <?= $sideMargin ?>;"><?= $receiptData['ReceiptDate'] ?></div> <!-- 610pt -->

			<div class="absolute with-line padded" style="left: <?= $sideMargin ?>; bottom: 742px; right: 248px;"><?= count($items) > 1 ? 'MISCELLANEOUS PRODUCT – SEE BELOW' : $description ?></div>

			<div class="absolute with-line padded" style="left: <?= $sideMargin ?>; bottom: 7.425in; right: 248px;"><?= $customerName ?></div>
			<div class="absolute with-line center" style="left: 6.375in; bottom: 713px; right: <?= $sideMargin ?>;">truck</div>

			<div class="absolute with-line center" style="left: 3.75in; bottom: 6.8in; right: 248px;">above</div>

			<div class="absolute" style="left: <?= $sideMargin ?>; top: 4.875in; right: <?= $sideMargin ?>;">
				<table class="item-table">
					<?php
					foreach ($pageItems as $idx => $item) {
					?>
						<tr class="first-line">
							<td style="width: 0.875in;"><?= number_format($item->getPieces()) ?></td>
							<td style="width: 0.875in;">Pcs</td>
							<td style="width: 248px;"><?= $item->Lot->Description ?></td>
							<td style="width: 1.125in;"><?= number_format($item->getWeight(), 2, '.', ',') ?></td>
							<td><?= $item->Lot->LotNumber ?></td>
						</tr>
						<tr class="second-line">
							<td colspan="2">&nbsp;</td>
							<td colspan="2">
								<?php
								if ($item->Lot->CustomerPONumber) echo "PO # " . $item->Lot->CustomerPONumber . "&nbsp;&nbsp;&nbsp;";
								if ($item->Lot->ProductCode) echo "PROD CODE: " . $item->Lot->ProductCode;
								?>
							</td>
							<td>&nbsp;</td>
						</tr>
					<?
						if (($idx + 1) % $LOTS_PER_PAGE == 0) {
							$nextPageItems = array_slice($pageItems, $idx + 1);
							break;
						}
					}
					?>
				</table>
			</div>

			<div class="absolute with-line center hide-rates" style="left: 1.5in; bottom: 2.875in; right: 5.75in;">$<?= $storage ?></div>
			<div class="absolute with-line padded hide-rates" style="left: 3in; bottom: 2.875in; right: 4.125in;"><?= $storageUnit ?></div>

			<div class="absolute with-line center" style="left: 1.875in; bottom: 2.625in; right: 4.125in;"><?= $receiptData['ReceiptDate'] ?></div>

			<div class="absolute with-line center hide-rates" style="left: 1.5in; bottom: 2.4in; right: 6.125in;">$<?= $handling ?></div>
			<div class="absolute with-line padded hide-rates" style="left: 2.625in; bottom: 2.4in; right: 4.875in;"><?= $handlingUnit ?></div>

			<div class="absolute with-line center" style="left: 1.5in; bottom: 2.15in; right: 6in;">as above</div>

			<div class="absolute with-line padded" style="left: 1.75in; bottom: 0.9in; right: 4in;"><?= $factoryName ?></div>
			<img class="absolute" style="left: 5.375in; width: 1.5in; bottom: 0.95in;" src="/public/images/signature.png" alt="signature">
			<div class="absolute center" style="left: 5in; bottom: 0.7in; right: <?= $sideMargin ?>;">Carl Doemel</div>
		</div>
	</div>

<?php
}
?>

<div class="page shorten-for-print warehouse-receipt">
	<div class="page-inner">
		<img src="/public/images/Warehouse_Receipt_P2.jpg" class="page-background" />
	</div>
</div>


<div class="hide-on-print">
	<pre></pre>
</div>


<div id="formContainer" class="left-fixed-container hide-on-print form-container">
	<div class="left-fixed-inner">
		<select name="addresses" id="selectAddresses" class="form-control" style="margin:1em 0;">
			<option value="" selected>Select an address</option>
			<option value="Oshkosh Storage Co.:1110 Industrial Ave., Oshkosh WI, 54901">Oshkosh</option>
			<option value="Oshkosh Cold Storage, LLC.:4385 County Road PP, Plymouth, WI, 53073">Plymouth</option>
			<option value="OCS Oostburg, LLC.:44 Enterprise Ct., Oostburg, WI, 53070">Oostburg</option>
		</select>
		<button type="button" class="btn btn-default" id="editReceipt">Edit Receipt</button>
		<br />
	</div>
	<div class="left-fixed-inner form-container-inner">
		<form class="form-horizontal" method="post" novalidate onsubmit="return false" id="receiptForm">
			<input type="hidden" value="<?php if ($receiptData['ReceiptID']) : ?><?= $receiptData['ReceiptID'] ?><?php endif ?>" name="ReceiptID" id="receiptFormReceiptID" />
			<input type="hidden" value="lotNumber" name="useField" id="receiptFormAction" />
			<div class="form-body">
				<div class="form-group control-group">
					<label class="col-4 control-label" for="ReceiptDate">Receipt Date</label>

					<div class="col-8">
						<input type="text" name="ReceiptDate" id="ReceiptDate" value="<?= $receiptData['ReceiptDate'] ?>" class="form-control datepicker" required data-validation-required-message="Please enter a Receipt Date" />
						<p class="help-block text-danger"></p>
					</div>
				</div>

				<?php if (is_array($lots) && count($lots) == 0) : ?>
					<div class="form-group control-group lot-input-container">
						<label class="col-4 control-label" for="Lot1">Lot #1</label>

						<div class="col-8">
							<input type="text" id="Lot1" class="form-control" name="Lots[]" value="">
							<p class="help-block text-danger"></p>
						</div>
					</div>
				<?php endif ?>

				<?php if (is_array($lots)) : ?>
					<?php foreach ($lots as $idx => $lot) : ?>
						<div class="form-group control-group lot-input-container">
							<label class="col-4 control-label lot-control-label" for="Lot<?= $idx + 1 ?>">
								<?php if ($idx > 0) : ?><i class="fa fa-trash fa-lg fa-fw removeLot" onClick="removeLot(this)"></i><?php endif; ?> Lot #<?= $idx + 1 ?>
							</label>

							<div class="col-8">
								<?php if ($idx == 0) : ?>
									<p class="ro-lotNum"><?= $lot['LotNumber'] ?></p>
									<input type="hidden" name="defaultLot" value="<?= $lot['LotNumber'] ?>">
								<?php else : ?>
									<input type="text" id="Lot<?= $idx + 1 ?>" class="form-control lotNumberSearch ui-autocomplete-input" autocomplete="off" onkeydown="lotAutoComplete(this)" name="Lots[]" value="<?= $lot['LotNumber'] ?>">
									<p class="help-block text-danger"></p>
								<?php endif; ?>
							</div>
						</div>
					<?php endforeach; ?>
				<?php endif ?>

				<div class="form-group control-group add-group">
					<div class="col-4 add-button-small-menu dark-red">
						<a href="#" id="AddToWR" title="Add to Warehouse Receipt" data-toggle="popover" data-lotid="<?= $lotData->LotID ?>">
							<i class="fa fa-plus fa-lg fa-fw dark-red"></i>
						</a>
					</div>
					<div class="col-8 dark-red"></div>
				</div>

			</div>

			<div class="action-container">
				<button type="button" class="btn btn-default close-edit">Close</button>
				<input type="submit" class="btn btn-primary" value="Save Receipt" />
			</div>
		</form>
	</div>
</div>
<style>
/* .norates-control {
    position: relative;
    top: 0.65in;
    left: 3.9in;
} */
</style>
<div class="right-fixed-container hide-on-print">
	<div class="right-fixed-inner">
		<button class="btn btn-primary print-button">Print</button>
	</div>
	<div class="right-fixed-inner">
		<label class="norates-control" for="norates"><input id="norates" name="norates" type="checkbox">Do not print rates</label>
	</div>
</div>

<script src="/public/js/bootstrap.min.js"></script>
<script src="/public/js/bootbox.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script type="text/javascript">
	$(document).ready(function() {

		$('#norates').click(function() {
			if ($('#norates').is(':checked')) {
				$('.hide-rates').addClass('hide-on-print').hide();
			}
			else {
				$('.hide-rates').removeClass('hide-on-print').show();
			}
		});

		$('.print-button').click(function() {
			const selectedValue = $('#selectAddresses').val();

			if (!selectedValue) {
				alert("Please select a warehouse address.");
			} else {
				if ($('#norates').is(':checked')) {
					$('.hide-rates').addClass('hide-on-print').hide();
				}
				window.print();
			}
		});
		var $formContInner = $('#formContainer .form-container-inner').hide();

		$('#editReceipt').click(function() {
			$formContInner.slideToggle()
		});

		$('.close-edit').click(function() {
			$formContInner.slideUp()
		});

		$(document).on("change", "#selectAddresses", function() {
			// Split the value at the colon
			var parts = $(document).find('#selectAddresses').val().split(':');

			// Assuming the format is "facilityName:facilityAddress"
			var facilityName = parts.length > 0 ? parts[0].trim() : "";
			var facilityAddress = parts.length > 1 ? parts[1].trim() : "";

			// Update the #facilityName element with the facilityName
			$(document).find("#facilityName").html(facilityName);

			$(document).find("#facilityNameFooter1").find(".facilityNameFooter1").html(facilityName);

			$(document).find("#facilityNameFooter2").find(".facilityNameFooter2").html(facilityName);

			// Update the #changeAddress element with the facilityAddress
			$(document).find("#facilityAddress").html(facilityAddress);
		});

		var $form = $('#receiptForm');

		$form.submit(function() {
			$.ajax({
				url: "/warehousereceipt/save",
				type: "POST",
				data: $form.serialize(),
				dataType: "json",
				success: function(data) {
					if (data.success == 1) {
						if (data.ReceiptID != '') {
							//window.location.href = '/warehousereceipt/print/'+data.ReceiptID;
							window.location.reload();
						} else {
							bootbox.alert(data.msg);
						}
					} else {
						bootbox.alert(data.msg);
					}
				}
			});

			return false;
		});
	});

	$(document).ready(function($) {
		$('#AddToWR').click(function() {
			var lastLot = $('.form-body').children().last().prev();
			var lotCount = $('.lot-input-container').length;

			var html = '<div class="form-group control-group lot-input-container">';
			html += '<label class="col-4 control-label lot-control-label" for="Lot' + (lotCount + 1) + '">'
			html += '<i class="fa fa-trash fa-lg fa-fw removeLot" onClick="removeLot(this)"></i> Lot #' + (lotCount + 1) + '</label>';
			html += '<div class="col-8">';
			html += '<input type="text" id="Lot' + (lotCount + 1) + '" class="form-control lotNumberSearch ui-autocomplete-input" autocomplete="off" onkeydown="lotAutoComplete(this)" name="Lots[]" value="">';
			html += '<p class="help-block text-danger"></p>';
			html += '</div>';
			html += '</div>';

			lastLot.after(html);
		});
	});

	function removeLot(element) {
		var elementToRemove = $(element).closest('.lot-input-container');
		var closestInput = elementToRemove.find('input');

		if ($(closestInput).val() == '') {
			elementToRemove.remove();
			renumberLots();
			return;
		}

		bootbox.confirm('Are you sure you want to remove lot ' + $(closestInput).val() + '?', function(result) {
			if (result) {
				elementToRemove.remove();
				renumberLots();
			}
		});
	}

	function renumberLots() {
		$('.lot-control-label').each(function(index, element) {
			if (index == 0) {
				$(element).text('Lot #' + (index + 1));
			} else {
				$(element).html('<i class="fa fa-trash fa-lg fa-fw removeLot" onClick="removeLot(this)"></i> Lot #' + (index + 1));
			}
		});
	}

	function lotAutoComplete(element) {
		$(element).autocomplete({
			source: function(request, response) {
				$.ajax({
					url: "/search/receiptlotnumber",
					type: "POST",
					dataType: "json",
					data: {
						searchVal: request.term,
						customerID: "<?= $receiptData['CustomerID'] ?>"
					},
					success: function(data) {
						response($.map(data, function(item) {
							return {
								label: item.name,
								id: item.id,
								abbrev: item.name
							};
						}));
					}
				});
			},
			minLength: 0,
			autoFocus: true
		});
	}
</script>

<style>
	.page-inner {
		top: -6pt;
	}

	img.page-background {
		position: absolute;
		top: 10px;
		left: 0;
		width: fit-content;
		height: inherit;
		z-index: 0;
	}

	table.ruler-table {
		position: absolute;
		width: 8.5in;
		height: auto;
		left: 0;
		top: 0;
		border-collapse: collapse;
		display: none;
	}

	table.ruler-table td {
		border: 1px solid black;
		width: 0.5in;
		height: 0.5in;
		padding: 0;
		line-height: 0.25;
		box-sizing: border-box;
	}

	table.ruler-table td:nth-child(odd) {
		border-right-color: #bbbbbb;
	}

	table.ruler-table tr:nth-child(odd) td {
		border-bottom-color: #bbbbbb;
	}


	table.item-table {
		width: 100%;
		border-collapse: collapse;
	}

	table.item-table tr.second-line td {
		padding-bottom: 0.125in;
		white-space: nowrap;
	}

	table.item-table td {
		font-size: inherit;
		line-height: inherit;
		margin: 0;
	}

	.padded {
		padding-left: 0.25in;
	}

	.form-container-inner {
		background-color: #fff;
		border: 1px solid #999;
		border: 1px solid rgba(0, 0, 0, 0.2);
		border-radius: 6px;
		-webkit-box-shadow: 0 3px 9px rgba(0, 0, 0, 0.5);
		box-shadow: 0 3px 9px rgba(0, 0, 0, 0.5);
		-webkit-background-clip: padding-box;
		background-clip: padding-box;
		outline: 0;
		padding: 15px;
		width: 360px;
		margin-top: 1em;
	}

	.form-horizontal .form-group {
		margin-left: -15px;
		margin-right: -15px;
	}

	.form-group {
		margin-bottom: 15px;
	}

	.form-horizontal .control-label {
		text-align: right;
		margin-bottom: 0;
		padding-top: 7px;
		display: inline-block;
		box-sizing: border-box;
		max-width: 100%;
		font-weight: bold;
		font-family: 'Open Sans', sans-serif;
		font-size: 14px;
		line-height: 1.42857143;
		color: #480303;
	}

	.dark-red {
		color: #480303;
	}

	.add-group>div {
		margin-bottom: .5rem;
	}

	.form-control {
		color: #222222;
		display: block;
		box-sizing: border-box;
		width: 100%;
		height: 34px;
		padding: 6px 12px;
		font-size: 14px;
		line-height: 1.42857143;
		background-color: #fff;
		background-image: none;
		border: 1px solid #ccc;
		border-radius: 4px;
		-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
		box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
		-webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
		-o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
		transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s
	}

	.form-horizontal .col-4,
	.form-horizontal .col-8,
	.form-horizontal .col-6 {
		position: relative;
		min-height: 1px;
		padding-left: 15px;
		padding-right: 15px;
	}

	.print-cert {
		margin-top: 1em;
		position: relative;
		top: 0.25in;
		left: 4.5in;
	}

	.bootbox-body h5,
	h4.modal-title {
		font-size: 1.2em;
		text-transform: uppercase;
		text-align: left;
		font-weight: bold;
		letter-spacing: 0.2em;
		color: #d6bd99;
		margin-bottom: .5rem;
	}

	.bootbox-body a {
		text-decoration: dotted underline;
	}

	.bootbox-body em {
		font-weight: bold;
		font-size: 1.2em;
		display: block;
		text-align: center;
		color: #800;
	}

	.ro-lotNum {
		margin-top: .5rem;
		text-align: left;
	}

	.removeLot {
		cursor: pointer;
	}
</style>

<?php
$this->partial("include/print_footer");
?>
