<?php

$title = !$userId ? 'Add New User' : 'Edit User';
$this->partial("include/header", array('title' => $title, 'header' => $title));
?>


<div class="row">
	<div class="col-md-12">

		<form class="form-horizontal form-track-change" method="post" novalidate>
			<!-- fake fields are a workaround for chrome autofill getting the wrong fields
			chrome(and maybe other browsers) just blindy fill in the first type="password" fields
			that it sees on a page
			-->
			<input style="display:none" type="text" name="fakeusernameremembered"/>
			<input style="display:none" type="password" name="fakepasswordremembered"/>
			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="FirstName">First Name</label>
				<div class="col-sm-10">
				  <input type="text"
					name="FirstName"
					id="FirstName"
					value="<?php echo isset($userData->FirstName) ? $userData->FirstName : '' ?>"
					class="form-control"
					required
					data-validation-required-message="Please enter a first name" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="LastName">Last Name</label>
				<div class="col-sm-10">
				  <input type="text"
					name="LastName"
					id="LastName"
					value="<?php echo isset($userData->LastName) ? $userData->LastName : '' ?>"
					class="form-control"
					required
					data-validation-required-message="Please enter a last name" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="LoginID">Username</label>
				<div class="col-sm-10">
				  <input type="text"
					name="LoginID"
					id="LoginID"
					value="<?php echo isset($userData->LoginID) ? $userData->LoginID : '' ?>"
					class="form-control"
					required
					data-validation-required-message="Please enter a username" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
			<label class="col-sm-2 control-label" for="Password">Password</label>
				<div class="col-sm-10">
				  <input type="password"
					id="Password"
					name="Password"
					class="form-control"
	<?php
					if ( !$userId ) {
						echo ' required data-validation-required-message="Please enter a password" ';
					}
	?>
					 />
	<?php
					if ( !$userId ) {
						echo '<p class="help-block text-danger"></p>';
					}
					else {
						echo '<span id="helpBlock" class="help-block helpBlockStandout">Leave blank to retain password, enter new password to update.</span>';
					}
	?>

				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="RolePID">Role</label>
				<div class="col-sm-10">
					<select
						id="RolePID"
						name="RolePID"
						class="form-control"
						required
						data-validation-required-message="Please select a role">
<?php
						foreach ( $roles as $role ) {
							$sel = '';
							if ( !empty($userData->RolePID) ) {
								$sel = $role['ParameterID'] == $userData->RolePID ? ' selected="selected" ' : '';
							}
							echo '<option value="' . $role['ParameterID'] . '"' . $sel . '>' . $role['Value1'] . '</option>';
						}
?>
					</select>
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="StatusPID">Status</label>
				<div class="col-sm-10">
					<select
						id="StatusPID"
						name="StatusPID"
						class="form-control"
						required
						data-validation-required-message="Please select a status">
<?php
						foreach ( $statuses as $status ) {
							$sel = '';
							if ( !empty($userData->StatusPID) ) {
								$sel = $status['ParameterID'] == $userData->StatusPID ? ' selected="selected" ' : '';
							}
							echo '<option value="' . $status['ParameterID'] . '"' . $sel . '>' . $status['Value1'] . '</option>';
						}
?>
					</select>
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="Email">Email</label>
				<div class="col-sm-10">
				  <input type="text"
					name="Email"
					id="Email"
					value="<?php echo isset($userData->Email) ? $userData->Email : '' ?>"
					class="form-control" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="Phone">Phone</label>
				<div class="col-sm-10">
				  <input type="text"
					name="Phone"
					id="Phone"
					value="<?php echo isset($userData->Phone) ? $userData->Phone : '' ?>"
					class="form-control" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-2 control-label" for="Fax">Fax</label>
				<div class="col-sm-10">
				  <input type="text"
					name="Fax"
					id="Fax"
					value="<?php echo isset($userData->Fax) ? $userData->Fax : '' ?>"
					class="form-control" />
					<p class="help-block text-danger"></p>
				</div>
			</div>


			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<input class="btn btn-primary" type="submit" name="saveUser" id="saveUser" value="Save User" />
	<?php
				if ( $userId ) {
	?>
				<input class="btn btn-default deleteUser" data-name="<?php echo $userData->FirstName . ' ' . $userData->LastName ?>" name="deleteUser" type="submit" value="Delete User" />
	<?php
				}
	?>
				</div>
			</div>
		</form>

	</div>
</div>

<?php

$this->partial("include/footer_start");
?>
<script src="/public/js/jqBootstrapValidation-1.3.7.min.js"></script>
<script>
var loginIds = <?php echo json_encode($loginIds); ?>;
jQuery(document).ready(function($) {

	$('#saveUser').click(function() {
		var loginId = $('#LoginID').val();
		loginId = loginId.toLowerCase();

		var loginIdOnPageLoad = <?php echo json_encode(strtolower($userData->LoginID)) ?>;
		if ( loginIdOnPageLoad != loginId && loginIds[loginId] ) {
			bootbox.alert('That username already exists. Please pick another one.');
			$('#LoginID').focus();
			return false;
		}

		<?php if ( $isCurrentUser ): ?>
			if ( $('#RolePID').val() != '<?= User::SU_ROLE_PID ?>' ) {
				return confirm('Warning: If you change your own role, you will no longer be able to access this page.');
			}
		<?php endif?>
	});

	$('.deleteUser').click(function() {
		var deleteIt = confirm('Are you sure you want to delete "' + $(this).data('name') + '"?');
		return deleteIt;
	});
});

jQuery(function () {
	jQuery("input,select,textarea").not("[type=submit]").jqBootstrapValidation({
		preventSubmit: true,
		submitError: function($form, event, errors) {
			// Here I do nothing, but you could do something like display
			// the error messages to the customer, log, etc.
		},
		submitSuccess: function($form, event) {
			// form has been submitted
		},
		filter: function() {
			return jQuery(this).is(":visible");
		}
	});
});

</script>
<?php
$this->partial("include/footer_end");
