<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link
		href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,400italic,500,500italic,600,600italic,700,700italic'
		rel='stylesheet' type='text/css'>


    <link href="/public/css/bootstrap.min.css" rel="stylesheet">
    <link href="/public/css/font-awesome.min.css" rel="stylesheet">
	<link href="/public/css/ocs-printable-forms.css?ver=3" rel="stylesheet">
	<link href="/public/css/ocs-print-rules.css?ver=3" rel="stylesheet" media="print">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

	<link href='/public/css/flex-print.css' rel='stylesheet' type='text/css'>
	<title><?php echo isset($title) ? $title : '' ?> | OCS Cheese Tracker</title>

</head>
