
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/public/js/bootstrap.min.js"></script>
    <script src="/public/js/bootbox.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
    <script src="/public/js/jquery.tablesorter.min.js"></script>
    <script src="/public/js/jquery.metadata.js"></script>

	<div class="subnav" id="footerNav">
        <strong>&copy; <?php echo date("Y"); ?> Oshkosh Cold Storage</strong> &bull;
		<a href="/parameter/list">Edit Parameters</a>
	</div>

  </body>
</html>
