<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo isset($title) ? $title : '' ?> | OCS Cheese Tracker</title>
	<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <!-- Load Open Sans from Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <!-- Bootstrap -->
    <link href="/public/css/bootstrap.min.css" rel="stylesheet">
    <link href="/public/css/font-awesome.min.css" rel="stylesheet">
    <link href="/public/css/tablesorter-themes/style.css" rel="stylesheet">
    <link href="/public/css/ocs.css?v=4.1" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<?php
	if ( isset($stylesheets) && is_array($stylesheets) )
	{
		foreach ( $stylesheets as $s ) {
			echo '<link rel="stylesheet" href="' . $s . '">';
		}
	}
?>
  </head>
  <body>

<?php if (strpos($_SERVER[ 'HTTP_HOST' ], 'fergdev.com') !== false): ?>
    <style>
    .navbar-default {
        background-color: #4e003b !important;
    }
    .navbar-default .navbar-nav > li:nth-child(2n+1) {
        background-color: #68004e !important;
    }
    </style>
<?php endif ?>

	<?php
	if ( !isset($hideNavBar) )
	{
		if ( $this->session->get('userAuth') ) {
			?>
			<nav class="navbar navbar-inverse navbar-static-top navbar-no-margin" id="authHeader">
				<div class="container">
					<div class="collapse navbar-collapse">
						<p class="navbar-text navbar-right">
							Welcome, <?= ucwords(strtolower($this->session->userAuth['FirstName'])) ?> | <a href="/logout" class="navbar-link">Logout</a>
						</p>
					</div>
				</div>
			</nav>
			<?php
		}
		?>
		<nav class="navbar navbar-default navbar-static-top navbar-no-margin" id="adminNav">
			<!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
			<div class="container">
				<div class="navbar-header">
				  <button data-target="#bs-example-navbar-collapse-6" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>
				  <div class="navbar-brand"><a href="/"><img src="/public/images/oshkosh_logo.png" /></a></div>
				</div>

				<?php
				$security = $this->getDI()['securityPlugin']
				?>
				<div id="bs-example-navbar-collapse-6" class="collapse navbar-collapse navbar-right">
				  <ul class="nav navbar-nav">
					<li><a href="/lot/new">
						<img src="/public/images/lot_ico.png">
						<div>New Lot</div>
					</a></li>
					<li><a href="/offer/new">
						<img src="/public/images/offer_ico.png">
						<div>New Offer</div>
					</a></li>
					<li><a href="/customer/list">
						<img src="/public/images/customers_ico.png">
						<div><!-- Manage<br /> -->Customers</div>
					</a></li>
					<li><a href="/vendor/list">
						<img src="/public/images/vendors_ico.png">
						<div><!-- Manage<br /> -->Vendors</div>
					</a></li>
					<li><a href="/factory/list">
						<img src="/public/images/factories_ico.png">
						<div><!-- Manage<br /> -->Factories</div>
					</a></li>
					<?php if ($security->hasPermission('access', 'user')): ?>
					<li><a href="/user/list">
						<img src="/public/images/users_ico.png">
						<div><!-- Manage<br /> -->Users</div>
					</a></li>
					<?php endif ?>
					<li><a href="/billoflading/list/1E732327-AD3E-42C1-9602-F505B3A75E7E">
						<img src="/public/images/shipping_ico.png">
						<div><!-- Manage<br /> -->Shipping</div>
					</a></li>
					<li><a href="/edidocument">
						<img src="/public/images/edi_ico.png">
						<!-- <img src="/edidocument/geticon" -->
						<div><!-- Manage<br /> -->EDI</div>
					</a></li>
					<?php if (!$security->hasPermission('access', 'user')): ?>
					<li style="width:110px"></li>
					<?php endif ?>
				  </ul>

				</div><!-- /.navbar-collapse -->
			</div>
		</nav>

			<div class="subnav">
				<div class="container">
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<div style="width: 40%; margin: 0 auto; min-height: 2.5em;">
		<?php
		if ( !isset($hideQuickSearch) )
		{
			?>
								<input type="text" name="quickSearch" id="quickSearch" value="" placeholder="Search By Customer Name/Lot #" class="form-control roundedBorder">
        <?php } ?>
							</div>
						</div>
					</div>
				</div>
			</div>

			<?php
	}

	echo '<div id="mainContainer" class="container">';

	if ( isset($header) )
	{
		$columns = 12;
		$rContent = '';
		$rightColumns = 0;

		if  ( isset($rightContent) and $rightContent ) {
			if (isset($wideRightContent) && $wideRightContent) {
				$rightColumns = 7;
				$columns = 5;
			} else {
				$rightColumns = 5;
			$columns = 7;
		}

			$rContent = '<div class="col-md-' . $rightColumns . '"><div class="pull-right">' . $rightContent . '</div></div>';
		}

		$classes = isset($headerIcon) ? "ocs-icon ocs-$headerIcon" : "";

		$html = <<<HTML
		<div class="row" id="pageTitle">
			<div class="col-md-{$columns}"><h1 class="$classes">{$header}</h1></div>
			{$rContent}
		</div>
HTML;
		echo $html;
	}
	// $this->flashSession->output();

    $messages = $this->flashSession->getMessages();
	if ( isset( $messages ) and count($messages) > 0) {

		$messageTypeCss = array(
			'success' => 'bg-success',
			'error' => 'bg-danger',
			'warning' => 'bg-danger',
			'notice' => 'bg-primary'
		);

?>
	<div class="row">
		<div class="col-md-12">
                <?php
                foreach ($messages as $messageType => $messageArray) {
                    foreach ($messageArray as $message) {
						$cssClass = $messageTypeCss[$messageType];
                        echo "<div class=\"$cssClass alert\">$message</div>";
                    }
                }
                ?>
        </div>
    </div>
<?php } ?>
