<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo isset($title) ? $title : '' ?> | OCS Cheese Tracker</title>

    <!-- Load Open Sans from Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <link href="/public/css/bootstrap.min.css" rel="stylesheet">
    <link href="/public/css/font-awesome.min.css" rel="stylesheet">
	<link href="/public/css/ocs-printable-forms.css?ver=3" rel="stylesheet">
	<link href="/public/css/ocs-print-rules.css?ver=3" rel="stylesheet" media="print">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<?php
	if ( isset($stylesheets) && is_array($stylesheets) )
	{
		foreach ( $stylesheets as $s ) {
			echo '<link rel="stylesheet" href="' . $s . '">';
		}
	}

    function get_browser_name($user_agent)
    {
        if (strpos($user_agent, 'Opera') || strpos($user_agent, 'OPR/')) return 'opera';
        elseif (strpos($user_agent, 'Edge')) return 'edge';
        elseif (strpos($user_agent, 'Chrome')) return 'chrome';
        elseif (strpos($user_agent, 'Safari')) return 'safari';
        elseif (strpos($user_agent, 'Firefox')) return 'firefox';
        elseif (strpos($user_agent, 'MSIE') || strpos($user_agent, 'Trident/7')) return 'ie';

        return 'Other';
    }

    $browser = get_browser_name($_SERVER['HTTP_USER_AGENT']); // strtolower( get_browser(null, true)['browser'] );
?>
  </head>
  <body class="browser-<?= $browser ?>">

