<?php

$widths = array('30%', '13%', '15%', '7%', '10%', '10%', '5%');

$this->partial(
	"include/header", 
	array(
		'title' => 'Customer Test', 
		'header' => 'Customer Test'
	)
);

?>

<div class="row">
	<div class="col-md-12">
	<table class="table table-striped">
      <thead>
        <tr>
          <th width="<?php echo $widths[0] ?>">Name</th>
          <th width="<?php echo $widths[1] ?>">Email</th>
          <th width="<?php echo $widths[2] ?>">Phone</th>
          <th width="<?php echo $widths[3] ?>">Fax</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td width="<?php echo $widths[0] ?>"><?php echo $customerData->Name ?></td>
          <td width="<?php echo $widths[1] ?>"><?php echo $customerData->Email ?></td>
          <td width="<?php echo $widths[2] ?>"><?php echo $customerData->Phone ?></td>
          <td width="<?php echo $widths[3] ?>"><?php echo $customerData->Fax ?></td>
        </tr>
      </tbody>
    </table>
    
    
<?php foreach ( $customerData->contact as $c ) : ?>
        <?= $c->FirstName . ' ' . $c->LastName ?></br>
<?php endforeach ?>
    
    
	</div>
</div>

<?php

$this->partial("include/footer_start");
?>
<?php
$this->partial("include/footer_end");
