<?php
$this->partial(
	"include/header", 
	array(
		'title' => 'Storage Billing Report', 
		'header' => "{$customer->Name} - Storage Billing Report"
	)
);
?>

<div class="row">
	<div class="col-md-12">
		<form id="storageReportForm" class="form-horizontal" style="display: block;" method="post" action="/customer/storagereportxls/<?= $customer->CustomerID ?>" novalidate>
			<div class="form-group control-group">
				<label class="col-sm-3 control-label nopadding">Start Date</label>
				<div class="col-sm-3 nopadding">
					<input type="text" class="form-control datepicker" 
							id="StartDate" 
							name="StartDate" 
							required
							data-validation-required-message="Start Date is required">
					<p class="help-block text-danger"></p>
				</div>
			</div>
			
			<div class="form-group control-group">
				<label class="col-sm-3 control-label nopadding">End Date</label>
				<div class="col-sm-3 nopadding">
					<input type="text" class="form-control datepicker" 
							id="EndDate" 
							name="EndDate" 
							required
							data-validation-required-message="End Date is required">
					<p class="help-block text-danger"></p>
				</div>
			</div>
			
			<input type="submit" class="btn btn-primary" value="Get Report">
		</form>
	</div>
</div>



<?php
$this->partial("include/footer_start");
?>

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$( ".datepicker" ).datepicker();
	});
</script>

<?php
$this->partial("include/footer_end");
?>
