<?php

$rContent = '<a href="#" id="addFactory" class="btn btn-primary" data-toggle="modal" data-target="#factoryModal">Add New Factory</a>';
$this->partial(
	"include/header",
	array(
		'title' => 'Factories',
		'header' => 'Factories',
		'headerIcon' => 'factories',
		'rightContent' => $rContent
	)
);

?>

<div class="row">
	<div class="col-md-12" id="factoryHtml"></div>
</div>

<?php

$this->partial("include/footer_start");
?>
<script src="/public/js/jqBootstrapValidation-1.3.7.min.js"></script>
<script>

function getFactories(callback)
{
	$.ajax({
		url: "/factory/getfactories",
		type: "GET",
		dataType: "html",
		success: function(factoryHtml) {
			$('#factoryHtml').html(factoryHtml);
			if ( callback ) {
				callback();
			}
		}
	});
}

jQuery(document).ready(function($) {

	$( "body" ).on( "click", ".editFactory", function() {

		var factoryID = $(this).data('factory-id');
		$.ajax({
			url: "/factory/getfactory/" + factoryID,
			type: "GET",
			dataType: "json",
			success: function(factory) {
				$('#FactoryID').val(factoryID);

				$('#deleteFactory').data('name', factory.Name);
				$('#deleteFactory').data('factory-id', factoryID);

				$('#factoryModalLabel').html('Edit Factory');
				$('#Name').val(factory.Name);
				$('#Number').val(factory.Number);
				$('#FacilityLocation').val(factory.FacilityLocation);
				var Active = parseInt(factory.Active) == 1 ? true : false;
				if ( Active ) {
					$('#Active').prop('checked', true);
				}
				else {
					$('#Active').prop('checked', false);
				}
				$('#factoryModal').modal('show');
				$('#deleteFactory').show();
			}
		});


		return false;
	});

	$( "body" ).on( "click", ".deleteFactory", function() {
		var factoryId = $(this).data('factory-id');
		var name = $(this).data('name');
		var deleteIt = bootbox.confirm('Are you sure you want to delete factory "' + name + '"?',
            function (result){
            if ( result ) {
                $.ajax({
                    url: "/factory/delete/" + factoryId,
                    type: "GET",
                    dataType: "json",
                    success: function(data) {
                        if ( data.success == 1 ) {
                            if ( $("#factoryModal").is(":visible") )
                            {
                                var mycallback = function() {
                                    $('#savedFeedback .successFeedback').html('Factory Deleted');
                                    $( "#savedFeedback" ).fadeIn( 1000, function() {
                                        $( "#savedFeedback" ).fadeOut( 1000, function() {
                                            $('#factoryModal').modal('hide');
                                        });
                                    });

                                };

                                getFactories(mycallback);
                            }
                            else
                            {
                                getFactories();
                            }
                        }
                        else {
                            bootbox.alert('An error occurred while deleting the factory.');
                        }
                    }
                });
            }
        });
		return false;
	});

	$('#addFactory').click(function() {
		$('#factoryModalLabel').html('Add Factory');
		$('#deleteFactory').hide();
		$('#factoryForm input[type="text"]').val('');
		$('#FactoryID').val('');
		$('#Active').prop('checked', true);
	});

	var factoryCallback = null;
	<?php if ( $factoryId ) : ?>
	factoryCallback = function() {
		$( "#editFactory<?= $factoryId ?>" ).trigger( "click" );
	};
	<?php endif ?>
	getFactories(factoryCallback);
});

jQuery(function () {
	jQuery("input,select,textarea").not("[type=submit]").jqBootstrapValidation({
		preventSubmit: true,
		submitError: function($form, event, errors) {
			// Here I do nothing, but you could do something like display
			// the error messages to the customer, log, etc.
		},
		submitSuccess: function($form, event) {
			// form has been submitted

			if ( $form[0].id == 'factoryForm' )
			{
				var mycallback = function() {
					$('#savedFeedback .successFeedback').html('Factory Saved');
					$( "#savedFeedback" ).fadeIn( 1000, function() {
						$( "#savedFeedback" ).fadeOut( 1000, function() {
							$('#factoryModal').modal('hide');
						});
					});

				};

				$.ajax({
					url: "/factory/save",
					type: "POST",
					data: $('#factoryForm').serialize(),
					dataType: "json",
					success: function(data) {
						if ( data.success == 1 ) {
							getFactories(mycallback);
						}
						else {
							bootbox.alert('An error occurred while adding the factory.');
						}
					}
				});

			}

		},
		filter: function() {
			return jQuery(this).is(":visible");
		}
	});
});

</script>

<div class="modal fade" id="factoryModal" tabindex="-1" role="dialog" aria-labelledby="factoryModalLabel" aria-hidden="true"><!--begin factory modal-->
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="factoryModalLabel">Add Factory</h4>
      </div>
		<form class="form-horizontal" method="post" novalidate onsubmit="return false" id="factoryForm">
			<input type="hidden" value="" name="FactoryID" id="FactoryID" />
		  <div class="modal-body">

			<div class="form-group control-group">
				<label class="col-sm-3 control-label" for="Name">Name</label>
				<div class="col-sm-9">
				  <input type="text"
					name="Name"
					id="Name"
					value=""
					class="form-control"
					required
					data-validation-required-message="Please enter a Factory Name" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-3 control-label" for="Name">Number</label>
				<div class="col-sm-9">
				  <input type="text"
					name="Number"
					id="Number"
					value=""
					class="form-control"
					required
					data-validation-required-message="Please enter a Factory Number" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-3 control-label" for="Name">Facility Location</label>
				<div class="col-sm-9">
				  <input type="text"
					name="FacilityLocation"
					id="FacilityLocation"
					value=""
					class="form-control"
					required
					data-validation-required-message="Please enter a Facility Location" />
					<p class="help-block text-danger"></p>
				</div>
			</div>

			<div class="form-group control-group">
				<label class="col-sm-3 control-label" for="Active">Active</label>
				<div class="col-sm-9">
				  <input type="checkbox"
					name="Active"
					id="Active"
					value="1"
					checked="checked"
					class="form-control" />
					<p class="help-block text-danger"></p>
				</div>
			</div>


		  </div>

		  <div class="modal-footer">
			<div class="pull-left has-success" id="savedFeedback" style="display: none;"><div class="control-label successFeedback">Factory Saved</div></div>
			<button type="button" class="btn btn-default closeModal" data-dismiss="modal">Close</button>
			<input type="button" class="btn btn-default deleteFactory" style="display: none;" id="deleteFactory" value="Delete Factory" />
			<input type="submit" class="btn btn-primary" value="Save Factory" />
		  </div>
		</form>

    </div>
  </div>
</div><!--end factory modal-->


<?php
$this->partial("include/footer_end");
