<?php

$rContent = '';
$this->partial(
	"include/header",
	array(
		'title' => $title,
		'header' => $title,
		'headerIcon' => 'edi',
		'rightContent' => $rContent
	)
);

?>

<?php
if ( isset( $details ) ) {
	$this->partial(
		"table/details",
		array(
			'details' => $details,
			'notes' => $notes
		)
	);
}

$this->partial(
	"table/builder",
	array(
		'headers' => $headers,
		'data' => $data,
		'cols' => $cols
	)
);
?>
<div class="row" id="autodetails">
	<div class="col-md-12" style="margin-bottom: 1em; text-align: center;">
		<?php if ( ! $ReadOnly ): ?>
			<a id="convert" type="button" class="btn btn-primary" href="#">Convert to Offer</a>
		<?php endif ?>
	</div>
</div>
<?php
$this->partial("include/footer_start");
?>
<style>
.bootbox-body h5,
h4.modal-title {
	font-size: 1.2em;
	text-transform: uppercase;
	text-align: left;
	font-weight: bold;
	letter-spacing: 0.2em;
	color: #d6bd99;
	margin-bottom: .5rem;

}
.bootbox-body a {
	text-decoration: dotted underline;
}
</style>
<script>
function createPendingOffer()
{

	var dialog = bootbox.dialog({
		title: 	'Converting',
		message: '<p><i class="fa fa-spin fa-spinner"></i> Converting incoming customer order to pending offer...</p>'
	});

	dialog.init(function(){
		url = "/customerorder/creatependingoffer/<?= $OrderID ?>/<?= $EDIDocID ?>";
		$.ajax({
			url: url,
			type: "POST",
			dataType: "json",
			success: function(data) {
				if ( data.success == 1 ) {
					dialog.find('.bootbox-body').html('Order converted to Draft Offer. <br>' + data.msg + 'See <a href="/offer/list/C478D7C5-25FC-439B-A5A4-A155493ABC08">Pending Offers</a> screen');
				}
				else {
					dialog.find('.bootbox-body').html('An error occurred while creating pending offer:\n' + data.msg);
				}
			}
		});
	});

}

jQuery(document).ready(function($) {
	$( '#convert' ).click( function(){
		bootbox.confirm(
			'This will create a pending offer.<br><br><em>Are you sure?</em>',
			function( result ) {
				if (result) {
					createPendingOffer();
				}
			}
		);
	} );



});
</script>



<?php
$this->partial("include/footer_end");
