<?php

$rContent = '';
$this->partial(
	"include/header",
	array(
		'title' => $title,
		'header' => $title,
		'headerIcon' => 'edi',
		'rightContent' => $rContent
	)
);
?>
<div id="subtitlelinks">
	<?php if ($title === 'Incoming Orders') { ?>
		<a href="/customerorder/list/<?= CustomerOrder::STATUS_OFFERPENDING ?>">See Converted Orders</a> |
	<?php } else { ?>
		<a href="/customerorder/list/">See Incoming Orders</a> |
	<?php } ?>
	
	<a href="/offer/list/<?= Offer::STATUS_EDIPENDING ?>">See Pending Offers</a> |
	<a href="/billoflading/list/<?= BillOfLading::STATUS_CREATED ?>">See Outgoing Shipments</a>
</div>

<?php
if ( isset( $details ) ) {
	$this->partial(
		"table/details",
		array(
			'details' => $details
		)
	);
}

$hasHighlights = isset($highlightingArray) && count($highlightingArray) > 0;
$specialMessage = $hasHighlights ? 'Duplicate Orders are Highlighted' : NULL;

$this->partial(
	"table/builder",
	array(
		'headers' => $headers,
		'data' => $data,
		'cols' => $cols,
		'hasHighlights' => $hasHighlights,
		'highlightArray' => $highlightingArray,
		'specialMessage' => $specialMessage
	)
);
?>

<?php
$this->partial("include/footer_start");
?>
<style>
.bootbox-body h5 {
	font-size: 1.2em;
	text-transform: uppercase;
	text-align: left;
	font-weight: bold;
	letter-spacing: 0.2em;
	color: #d6bd99;
	margin-bottom: .5rem;
}
</style>
<script>
jQuery(document).ready(function($) {
	$( '#autotable tr' ).click( function(){
		rowid = $( this ).attr( 'id' );
		parts = rowid.split( '-' );
		location.href="/customerorder/incomingdetail/" + parts[1];
	});
});
</script>




<?php
$this->partial("include/footer_end");
